server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: admin
    username: admin
    url: jdbc:mysql://localhost:8080/timeline
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop