insert into template_card(id, def_invention, invention_date) VALUES (1, 'Agriculture', -8000);
insert into template_card(id, def_invention, invention_date) VALUES (2, 'Asteroids', 1801);
insert into template_card(id, def_invention, invention_date) VALUES (3, 'Black Powder', 950);
insert into template_card(id, def_invention, invention_date) VALUES (4, 'Cave Painting', -30000);
insert into template_card(id, def_invention, invention_date) VALUES (5, 'ceramics', -6000);
insert into template_card(id, def_invention, invention_date) VALUES (6, 'figerprinting', 1902);
insert into template_card(id, def_invention, invention_date) VALUES (7, 'firebuilding', -450000);
insert into template_card(id, def_invention, invention_date) VALUES (8, 'garbage bags', 1950);
insert into template_card(id, def_invention, invention_date) VALUES (9, 'glasses', 1315);
insert into template_card(id, def_invention, invention_date) VALUES (10, 'impression, sunrise', 1872);
insert into template_card(id, def_invention, invention_date) VALUES (11, 'lightning rods', 1752);
insert into template_card(id, def_invention, invention_date) VALUES (12, 'lord of the rings', 1954);
insert into template_card(id, def_invention, invention_date) VALUES (13, 'mount rushmore', 1941);
insert into template_card(id, def_invention, invention_date) VALUES (14, 'paper', -200);
insert into template_card(id, def_invention, invention_date) VALUES (15, 'penicillin', 1928);
insert into template_card(id, def_invention, invention_date) VALUES (16, 'roleplaying games', 1974);
insert into template_card(id, def_invention, invention_date) VALUES (17, 'rubber eraser', 1770);
insert into template_card(id, def_invention, invention_date) VALUES (18, 'satellites', 1957);
insert into template_card(id, def_invention, invention_date) VALUES (19, 'sign language', 1620);
insert into template_card(id, def_invention, invention_date) VALUES (20, 'stonecutting', -2000000);
insert into template_card(id, def_invention, invention_date) VALUES (21, 'television', 1923);
insert into template_card(id, def_invention, invention_date) VALUES (22, 'the newspaper', 1605);
insert into template_card(id, def_invention, invention_date) VALUES (23, 'the accordion', 1829);
insert into template_card(id, def_invention, invention_date) VALUES (24, 'the airplane', 1903);
insert into template_card(id, def_invention, invention_date) VALUES (25, 'the atomic bomb', 1945);
insert into template_card(id, def_invention, invention_date) VALUES (26, 'the ballpoint pen', 1953);
insert into template_card(id, def_invention, invention_date) VALUES (27, 'the brick', -7000);
insert into template_card(id, def_invention, invention_date) VALUES (28, 'the cannon', 1313);
insert into template_card(id, def_invention, invention_date) VALUES (29, 'the catapult', -397);
insert into template_card(id, def_invention, invention_date) VALUES (30, 'the celsius scale', 1741);
insert into template_card(id, def_invention, invention_date) VALUES (31, 'the cinematograph', 1895);
insert into template_card(id, def_invention, invention_date) VALUES (32, 'the compact disc', 1979);
insert into template_card(id, def_invention, invention_date) VALUES (33, 'the compass', 1090);
insert into template_card(id, def_invention, invention_date) VALUES (34, 'the computer mouse', 1968);
insert into template_card(id, def_invention, invention_date) VALUES (35, 'the crossbow', -400);
insert into template_card(id, def_invention, invention_date) VALUES (36, 'the diving suit', 1679);
insert into template_card(id, def_invention, invention_date) VALUES (37, 'the electric battery', 1800);
insert into template_card(id, def_invention, invention_date) VALUES (38, 'the electric light bulb', 1879);
insert into template_card(id, def_invention, invention_date) VALUES (39, 'the encyclopedia', 1751);
insert into template_card(id, def_invention, invention_date) VALUES (40, 'the globe', 1492);
insert into template_card(id, def_invention, invention_date) VALUES (41, 'the hourglass', 900);
insert into template_card(id, def_invention, invention_date) VALUES (42, 'the hypodemic syringe', 1841);
insert into template_card(id, def_invention, invention_date) VALUES (43, 'the internal combustion engine', 1860);
insert into template_card(id, def_invention, invention_date) VALUES (44, 'the laptop computer', 1981);
insert into template_card(id, def_invention, invention_date) VALUES (45, 'the locomotive', 1804);
insert into template_card(id, def_invention, invention_date) VALUES (46, 'the microscope', 1615);
insert into template_card(id, def_invention, invention_date) VALUES (47, 'the milk carton', 1915);
insert into template_card(id, def_invention, invention_date) VALUES (48, 'the model T', 1908);
insert into template_card(id, def_invention, invention_date) VALUES (49, 'the motorcycle', 1868);
insert into template_card(id, def_invention, invention_date) VALUES (50, 'the photocopier', 1938);
insert into template_card(id, def_invention, invention_date) VALUES (51, 'the pull tab can', 1962);
insert into template_card(id, def_invention, invention_date) VALUES (52, 'the pythagorean theoreme', -548);
insert into template_card(id, def_invention, invention_date) VALUES (53, 'the rabies vaccine', 1885);
insert into template_card(id, def_invention, invention_date) VALUES (54, 'the safe', 1844);
insert into template_card(id, def_invention, invention_date) VALUES (55, 'the screw', -500);
insert into template_card(id, def_invention, invention_date) VALUES (56, 'the smart card', 1974);
insert into template_card(id, def_invention, invention_date) VALUES (57, 'the statue of liberty', 1886);
insert into template_card(id, def_invention, invention_date) VALUES (58, 'the telegraph', 1837);
insert into template_card(id, def_invention, invention_date) VALUES (59, 'the telephone', 1876);
insert into template_card(id, def_invention, invention_date) VALUES (60, 'the telescope', 1668);
insert into template_card(id, def_invention, invention_date) VALUES (61, 'the termometer', 1593);
insert into template_card(id, def_invention, invention_date) VALUES (62, 'the toothbrush', 1498);
insert into template_card(id, def_invention, invention_date) VALUES (63, 'the transistor', 1948);
insert into template_card(id, def_invention, invention_date) VALUES (64, 'the tuning fork', 1711);
insert into template_card(id, def_invention, invention_date) VALUES (65, 'the typewriter', 1873);
insert into template_card(id, def_invention, invention_date) VALUES (66, 'the watch', 1504);
insert into template_card(id, def_invention, invention_date) VALUES (67, 'the wheel', -3500);
insert into template_card(id, def_invention, invention_date) VALUES (68, 'the zeppelin', 1900);
insert into template_card(id, def_invention, invention_date) VALUES (69, 'uranus', 1781);
insert into template_card(id, def_invention, invention_date) VALUES (70, 'whiskey', 1424);
insert into template_card(id, def_invention, invention_date) VALUES (71, 'writing', -3400);
